language: erlang
otp_release:
   - 18.0
   - 18.1

branches:
  only:
    - master

sudo: false

addons:
  apt:
    packages:
      - build-essential
      - libssl-dev
      - libexpat1-dev

script:
  - "make"
#  - "make tests"

notifications:
  email:
    recipients:
      - erocci-dev@ow2.org
    on_success: change
    on_failure: always
